# 在 Streamlit Cloud Secrets 文本框中粘贴以下内容
gemini_api_key = "AIzaSyAMXQSL82VY0KKwIhrkJBwiGfZnRc4ECTU"
imgbb_api_key = "e4430c1a4bca788c33cbf502a683d48b"
feedback_db_url = "libsql://feedback-coolfangtao.aws-us-east-2.turso.io"
feedback_db_token = "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3NjA5NjcwMTksImlkIjoiYmZlMjIyZTMtZmYwNy00ZTMwLWE1OTYtYjJiYjY3NWY0ODkyIiwicmlkIjoiMDIxNjZkNzMtYmU2Zi00NDg5LWFjYzMtZDAwNjJlZjI1ZGEzIn0.14DLAfTjdupIzv6Cy3WK-KUY4KsG7ijB9LMqPv6ph7d2MxiD5_Zef1EkWrUjuWioGLjPNGrg_xnlazONhZSyDw"