# 在 Streamlit Cloud Secrets 文本框中粘贴以下内容
API_KEY = "AIzaSyAMXQSL82VY0KKwIhrkJBwiGfZnRc4ECTU"
IMGBB_API_KEY = "e4430c1a4bca788c33cbf502a683d48b"
db_url = "https://your-feedback-db-coolfangtao.turso.io"
auth_token = "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3NjA5NjM5MjksImlkIjoiODJlZjRkOTctMTEwYy00MjFiLTk1ZTQtNjViNzFkMjQ4ZjgzIiwicmlkIjoiODYxNTdhM2EtYjM4Yi00NzFkLWJjNzAtMDRlZmM0YjVjZTY3In0.SI1_W_MjZ7A4H4XzDMsbHAzCGbdzTNLguyPEkjfEjOPFGNVg5Pqc8CoYHRnrMcAira7Tz_xjXxyL2AAbNvG1Dg"